name = "CometLogger"
uuid = "952f05d4-56a3-4431-900f-8abaa653b4db"
authors = ["rejuvyesh <mail@rejuvyesh.com> and contributors"]
version = "0.1.0"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
ColorTypes = "0.7, 0.8, 0.9, 0.10"
julia = "1"
PyCall = "1.0, 2.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
