name = "CometLogger"
uuid = "952f05d4-56a3-4431-900f-8abaa653b4db"
authors = ["rejuvyesh <mail@rejuvyesh.com> and contributors"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.5.3"

[targets]
test = ["Test"]
